#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

# Install w0nko irc server
echo "* Install w0nko irc server"
pkg_add http://pkgsrc.smartos.skylime.net/skylime-extra/2014Q2/x86_64/w0nko-13.11-dev.tgz

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
